In [1]:
a=10
print(type(a))


<class 'int'>


In [2]:
lst1=[90,85,89,71]
print(90 in lst1)

True


functions


In [3]:
def addition(a,b):
    return a+b

In [4]:
addition(56,78)

134

In [5]:
def taxcal(S,T):
    Tax=((T/100)*S)
    return Tax
    

In [6]:
taxcal(3000,5)

150.0

In [12]:
def tax(sal):
    if sal>0 and sal<10000:
        return 0.05*sal
    elif sal>=10000 and sal<50000:
        return 0.1*sal
    elif sal>=50000 and sal<200000:
        return 0.15*sal
    elif sal>=200000:
        return 0.2*sal
    else:
        print("enter valid salary")


        
    
    



In [15]:
tax(200000)

40000.0

In [16]:
tax(-90)

enter valid salary


In [17]:
tax(10000)

1000.0

w=[67,45,23,50]
h=[160,127,140,187]
output:bmi=w/h^2


In [21]:
w=[67,45,23,50]
h=[1.60,1.27,1.40,1.87]
for i,j in zip(w,h):
    print(i /(j*j))

26.171874999999996
27.900055800111602
11.734693877551022
14.298378563870855


In [22]:
for i in range(len(w)):
    print(w[i] / (h[i]*h[i]))

26.171874999999996
27.900055800111602
11.734693877551022
14.298378563870855


numpy

In [23]:
lst1=[90,56,12,34]
lst2=[78,45,55,67]
print(lst1+lst2)

[90, 56, 12, 34, 78, 45, 55, 67]


In [27]:
import numpy as np
arr1=np.array([90,56,12,34])
arr2=np.array([78,45,55,67])
print(arr1+arr2)

[168 101  67 101]


In [28]:
arr1=np.zeros((2,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
arr2=np.ones((2,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
arr3=np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
arr4=np.array([[3,5,7], [9,6,1]])
print(arr4)
print(np.ndim(arr4))
print(np.shape(arr4))


[[3 5 7]
 [9 6 1]]
2
(2, 3)


In [35]:
arr5=np.array([4,5,6,7,8,1,3,6])


In [38]:
arr5=arr5.reshape(4,2)

In [39]:
arr5

array([[4, 5],
       [6, 7],
       [8, 1],
       [3, 6]])

In [40]:
arr6=np.array([4,5,8,9,7,8,1,3])



In [43]:
arr6.resize(4,2)

In [46]:
arr6

array([[4, 5],
       [8, 9],
       [7, 8],
       [1, 3]])

In [47]:
arr6=np.arange(10,50).reshape(8,5)
print(arr6)
print(np.shape(arr6))

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
(8, 5)


In [48]:
arr7=np.arange(8,1001,8) #start,stop,step
print(arr7)


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [49]:
multiple_seven=np.arange(7,701,7) #start,stop,step
print(multiple_seven)


[  7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119 126
 133 140 147 154 161 168 175 182 189 196 203 210 217 224 231 238 245 252
 259 266 273 280 287 294 301 308 315 322 329 336 343 350 357 364 371 378
 385 392 399 406 413 420 427 434 441 448 455 462 469 476 483 490 497 504
 511 518 525 532 539 546 553 560 567 574 581 588 595 602 609 616 623 630
 637 644 651 658 665 672 679 686 693 700]


In [50]:
arr10=np.array ( [ [[1,2,3], [4,5,6]],[[4,5,2],[3,6,0]] ] )
print(arr10)
print(np.shape(arr10)) #group, row, column
print(np.ndim(arr10))

[[[1 2 3]
  [4 5 6]]

 [[4 5 2]
  [3 6 0]]]
(2, 2, 3)
3


In [51]:
arr9=np.linspace(2,8,6) # generate 6 evenly numbers 2,$,$,$,$,8
print(arr9)

[2.  3.2 4.4 5.6 6.8 8. ]


matrix operations

In [55]:
mat1=np.array([9,4,6,7]).reshape(2,2)
mat2=np.array([1,2,3,4]).reshape(2,2)
print("Matrix 1:", mat1)
print("Matrix 2:", mat2)

Matrix 1: [[9 4]
 [6 7]]
Matrix 2: [[1 2]
 [3 4]]


In [56]:
print(mat1*mat2)

[[ 9  8]
 [18 28]]


In [57]:
print(mat1.dot(mat2))

[[21 34]
 [27 40]]


In [58]:
print(mat1@mat2)

[[21 34]
 [27 40]]


In [59]:
print(np.linalg.inv(mat1))

[[ 0.17948718 -0.1025641 ]
 [-0.15384615  0.23076923]]


statstics

In [60]:
ar1=np.array([90,45,34,16,23,12])
print(np.mean(ar1))

36.666666666666664


In [61]:
print(np.median(ar1)) # 12,16,23,34,45,90

28.5


In [62]:
print(np.std(ar1)) #standard deviation

26.278423764669668


In [63]:
print(np.var(ar1))  #variance

690.5555555555557


trignometry

In [64]:
print(np.pi)

3.141592653589793


In [66]:
rad=[90,30,45]
for i in rad:
    print(np.sin(i))

0.8939966636005579
-0.9880316240928618
0.8509035245341184


In [67]:
rad=[90,30,45]
for i in rad:
    print(np.cos(i))

-0.4480736161291701
0.15425144988758405
0.5253219888177297


In [68]:
rad=[90,30,45]
for i in rad:
    print(np.tan(i))

-1.995200412208242
-6.405331196646276
1.6197751905438615


In [70]:
deg=[np.pi/4,np.pi/2,np.pi/3]
for i in deg:
    print(np.sin(i))

0.7071067811865476
1.0
0.8660254037844386


airthematic operation

In [71]:
a=np.array([8,9,1])
b=np.array([2,5,8])
print(np.sum((a,b)))

33


In [72]:
print(np.cumsum(a))

[ 8 17 18]


In [73]:
c = np.array([[1,2,3],[6,7,3],[9,1,6]])
print(np.cumsum(c, axis=0)) #column

[[ 1  2  3]
 [ 7  9  6]
 [16 10 12]]


In [74]:
print(np.cumsum(c, axis=1)) 

[[ 1  3  6]
 [ 6 13 16]
 [ 9 10 16]]


In [75]:
print(np.prod((a,b)))

5760


In [76]:
print(np.cumprod(c))

[    1     2     6    36   252   756  6804  6804 40824]


In [77]:
print(np.cumprod(c,axis=0))


[[ 1  2  3]
 [ 6 14  9]
 [54 14 54]]


In [78]:
print(np.cumprod(c,axis=1))

[[  1   2   6]
 [  6  42 126]
 [  9   9  54]]


In [79]:
s1=np.array([90,23,40,12])
s2=np.array([10,2,11,5])
print(np.mod(s1,s2))

[0 1 7 2]


In [80]:
print(np.divmod(s1,s2))

(array([ 9, 11,  3,  2]), array([0, 1, 7, 2]))


In [108]:
num1=81
num2=99
num3=78
print(np.sqrt(num1))

9.0


In [109]:
print(np.lcm(num1,num2))

891


In [111]:
print(np.gcd(num1,num2))

9


In [112]:
aa=[45,67,89]
print(np.lcm.reduce(aa))

268335


In [113]:
print(np.gcd.reduce(aa))

1


In [114]:
ab=np.array([0,-4,34,-6,45])
print(np.absolute(ab))

[ 0  4 34  6 45]


logarithms

In [115]:
n=45
print(np.log(n))

3.8066624897703196


In [116]:
print(np.log10(n))

1.6532125137753437


In [117]:
print(np.log2(n))

5.491853096329675


universal functions

In [81]:
a=np.array([56,78,12,32,111,109])
print(max(a))

111


In [82]:
print(min(a))

12


sorting

In [83]:
b=np.array([90,12,45,1,89,98])
b.sort()
print(b)

[ 1 12 45 89 90 98]


In [85]:
c=np.array([90,12,45,1,89,98])
d=sorted(c)
print(d)
print(c)

[1, 12, 45, 89, 90, 98]
[90 12 45  1 89 98]


rounding

In [86]:
s2=np.array([9.1,-7.8])
print(np.ceil(s2))

[10. -7.]


In [87]:
s2=np.array([9.1,-7.8])
print(np.floor(s2))

[ 9. -8.]


random module

In [90]:
import numpy.random as rd

In [92]:
ran1=rd.rand(2) #0 to 1
print(ran1)

[0.6675868  0.02750521]


In [97]:
ran2=rd.randint(5) #0 to 1
print(ran2)

4


In [98]:
ran3=rd.randint(5, size=(6))
print(ran3)


[4 4 4 0 0 2]


In [99]:
ran4=rd.randint(5, size=(6,2,3))
print(ran4)

[[[2 4 1]
  [2 2 3]]

 [[3 2 2]
  [1 1 4]]

 [[3 0 3]
  [0 1 3]]

 [[0 2 3]
  [2 3 3]]

 [[2 3 4]
  [1 3 1]]

 [[2 4 4]
  [1 2 2]]]


stack

In [100]:
ar1=np.array([[1,5,6],[3,4,5]])
ar2=np.array([[2,7,6],[33,4,15]])
print(ar1)
print("\n")
print(ar2)

[[1 5 6]
 [3 4 5]]


[[ 2  7  6]
 [33  4 15]]


In [102]:
ar3=np.hstack((ar1,ar2)) # side by side
print(ar3)

[[ 1  5  6  2  7  6]
 [ 3  4  5 33  4 15]]


In [104]:
ar4=np.vstack((ar1,ar2)) # one top of another
print(ar4)

[[ 1  5  6]
 [ 3  4  5]
 [ 2  7  6]
 [33  4 15]]


In [106]:
ar5=np.arange(1,13).reshape(3,2,2)
print(ar5)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [107]:
ar6=np.dstack(ar5)
print(ar6)

[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]


set

In [118]:
s1=np.array([9,3,5,7])
s2=np.array([3,7,8,9])
print(np.union1d(s1,s2))

[3 5 7 8 9]


In [119]:
print(np.intersect1d(s1,s2))

[3 7 9]


In [120]:
print(np.setdiff1d(s1,s2))

[5]


search

In [121]:
col1=np.array([44,33,12,67,19])
index=np.where(col1%2==0)
print(index)

(array([0, 2], dtype=int64),)


In [135]:
col2 =np.array([45,33,21,50,60,15])
num=np.where((col2%5==0) &(col2%3==0))
print(num)

(array([0, 4, 5], dtype=int64),)
